version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: s2media_postgres_dev
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=s2media
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    container_name: s2media_redis_dev
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
