version: '3.9'
services:
  api:
    container_name: s2media_server
    build:
      context: ./apps/server
      dockerfile: ./Dockerfile.dev
    depends_on:
      - db
      - redis
    ports:
      - 5000:5000
      - 5555:5555
    env_file:
      - ./apps/server/.env
    volumes:
      - ./apps/server:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/s2media?schema=public&connection_limit=5&pool_timeout=0
      - REDIS_HOST=redis

  db:
    image: postgres:latest
    container_name: s2media_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=s2media
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  redis:
    image: redis:latest
    container_name: s2media_redis
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
