name: Deploy server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Navigate to server
        run: cd ./apps/server

      - name: Install packages in server
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build project
        run: yarn build

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
