name: Deploy server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install root packages
        run: yarn install --frozen-lockfile

      - name: Install packages in server
        run: yarn install:server

      - name: Lint
        run: yarn lint:server

      - name: Build project
        run: yarn build:server

      - name: Install Railway
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Deploy
        run: cd ./apps/server && railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
